VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Planilha1"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Private Sub CommandButton1_Click()
Inseri_dados

End Sub

Private Sub CommandButton2_Click()
limpeza
End Sub

Private Sub CommandButton3_Click()
busca_data
End Sub

Private Sub CommandButton4_Click()
consulta
End Sub
